## PROJECT 4 TEAM 2
### Demographic Data Acquistion, Cleaning, Merging
#### Kade, Marcus, Erin

In [2]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

#### American Community Survey 2019 data: 5-year estimates.
##### Start with age and sex.
- We used the metadata descriptions from this file: `ACSST5Y2019.S0101_metadata_2021-10-06T131343.csv` to choose the desired columns.

- To keep things less busy, we created a columns_of_interest list for each .csv that we read in and used that during the `pd.read_csv()` process.

In [3]:
# Specify columns of interest.
acs2019_age_sex_columns_of_interest = ['GEO_ID', 
                                      'NAME', 
                                      'S0101_C01_001E', 
                                      'S0101_C01_032E',
                                      'S0101_C01_033E',
                                      'S0101_C02_022E',
                                      'S0101_C02_026E',
                                      'S0101_C02_030E',
                                      ]
                                      

# Read in the data. skiprows = 1 removes the verbose first row that was acting like a second header; it was forcing numeric columns to be objects.

acs2019_age_sex = pd.read_csv(
    '../data/02_demo_data/ACS/ACS_2019_age_and_sex_by_county/ACSST5Y2019.S0101_data_with_overlays_2021-10-06T131343.csv',
    usecols = acs2019_age_sex_columns_of_interest,
    skiprows=[1])
    

# Assigning new column names.
# Prior to renaming columns we ran the import without skipping the row just to ensure the column naming conventions matched up.
acs2019_age_sex.columns = ['geo_id', 
                          'name',
                          'total_pop_age_sex',
                          'median_age',
                          'sex_ratio_males',
                          'under_18_percent',
                          'over_18_percent',
                          'over_65_percent'
                         ]
acs2019_age_sex.head(3)

geo_id                     name  total_pop_age_sex  median_age  \
0  0500000US01001  Autauga County, Alabama              55380        38.2   
1  0500000US01003  Baldwin County, Alabama             212830        43.0   
2  0500000US01005  Barbour County, Alabama              25361        40.4   

   sex_ratio_males  under_18_percent  over_18_percent  over_65_percent  
0             94.7              23.8             76.2             15.0  
1             94.7              21.7             78.3             20.0  
2            112.4              20.9             79.1             18.6

##### Create a little function to clean up the imported dataframes.

In [4]:
def clean_acs(df):
    df[['county', 'state']] = df['name'].str.split(',', expand = True)
    df['fips'] = df['geo_id'].str[-5:]
    df.drop(columns = ['geo_id', 'name'], inplace = True)
    df.set_index('fips', inplace = True)
    df = df[df['state'].str.contains('Puerto') == False]
    return df

#### Note that we'll end up with duplicate `county` and `state` columns in each of these dataframes if we don't take care of it. We'll keep them from the first dataframe and drop the other ones after they serve their purpose for dropping Puerto Rico.

In [5]:
acs2019_age_sex_clean = clean_acs(acs2019_age_sex)
acs2019_age_sex_clean

total_pop_age_sex  median_age  sex_ratio_males  under_18_percent  \
fips                                                                      
01001              55380        38.2             94.7              23.8   
01003             212830        43.0             94.7              21.7   
01005              25361        40.4            112.4              20.9   
01007              22493        40.9            117.5              20.6   
01009              57681        40.7             97.6              23.2   
...                  ...         ...              ...               ...   
56037              43521        35.3            106.8              26.5   
56039              23280        39.3            112.5              19.1   
56041              20479        35.8            103.3              29.2   
56043               8027        42.9            102.6              24.6   
56045               7049        43.1            111.7              21.0   

       over_18_percent  over_65_percent             county     state  
fips                                                                  
01001             76.2             15.0     Autauga County   Alabama  
01003             78.3             20.0     Baldwin County   Alabama  
01005             79.1             18.6     Barbour County   Alabama  
01007             79.4             15.9        Bibb County   Alabama  
01009             76.8             17.9      Blount County   Alabama  
...                ...              ...                ...       ...  
56037             73.5             11.4  Sweetwater County   Wyoming  
56039             80.9             14.0       Teton County   Wyoming  
56041             70.8             13.0       Uinta County   Wyoming  
56043             75.4             21.1    Washakie County   Wyoming  
56045             79.0             19.4      Weston County   Wyoming  

[3142 rows x 8 columns]

In [6]:
acs2019_age_sex.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3220 entries, 01001 to 72153
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   total_pop_age_sex  3220 non-null   int64  
 1   median_age         3220 non-null   float64
 2   sex_ratio_males    3220 non-null   float64
 3   under_18_percent   3220 non-null   float64
 4   over_18_percent    3220 non-null   float64
 5   over_65_percent    3220 non-null   float64
 6   county             3220 non-null   object 
 7   state              3220 non-null   object 
dtypes: float64(5), int64(1), object(2)
memory usage: 226.4+ KB


##### Next, read in the ACS 2019 income data columns of interest. We used `ACSST5Y2019.S1901_metadata_2021-10-05T144610.csv` to choose the desired columns.

In [7]:
# Specify columns of interest.
acs2019_income_columns_of_interest = ['GEO_ID', 
                                      'NAME', 
                                      'S1901_C01_001E', 
                                      'S1901_C01_012E', 
                                      'S1901_C01_013E', 
                                      'S1901_C02_001E', 
                                      'S1901_C02_012E', 
                                      'S1901_C02_013E'
                                     ]

acs2019_income = pd.read_csv(
    '../data/02_demo_data/ACS/ACS_2019_income_by_county/ACSST5Y2019.S1901_data_with_overlays_2021-10-05T144610.csv',
    usecols = acs2019_income_columns_of_interest,
    skiprows=[1])


# Clean up the naming conventions.
acs2019_income.columns = ['geo_id', 
                          'name',
                          'total_hh',
                          'median_hh_income',
                          'mean_hh_income',
                          'total_families',
                          'median_family_income',
                          'mean_family_income',
                          ]

acs2019_income.head(3)

geo_id                     name  total_hh  median_hh_income  \
0  0500000US01001  Autauga County, Alabama     21397             58731   
1  0500000US01003  Baldwin County, Alabama     80930             58320   
2  0500000US01005  Barbour County, Alabama      9345             32525   

   mean_hh_income  total_families  median_family_income  mean_family_income  
0           75326           15076                 71103               87094  
1           80986           53467                 75850               97991  
2           47068            6187                 41704               56374

In [8]:
acs2019_income.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3220 entries, 0 to 3219
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   geo_id                3220 non-null   object
 1   name                  3220 non-null   object
 2   total_hh              3220 non-null   int64 
 3   median_hh_income      3220 non-null   int64 
 4   mean_hh_income        3220 non-null   int64 
 5   total_families        3220 non-null   int64 
 6   median_family_income  3220 non-null   int64 
 7   mean_family_income    3220 non-null   int64 
dtypes: int64(6), object(2)
memory usage: 201.4+ KB


In [9]:
# Call the dataframe cleaning function.
acs2019_income_clean = clean_acs(acs2019_income)
acs2019_income_clean.drop(columns = ['state', 'county'], inplace = True)
acs2019_income_clean

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


total_hh  median_hh_income  mean_hh_income  total_families  \
fips                                                                
01001     21397             58731           75326           15076   
01003     80930             58320           80986           53467   
01005      9345             32525           47068            6187   
01007      6891             47542           60182            4789   
01009     20847             49358           65639           14874   
...         ...               ...             ...             ...   
56037     15523             74843           85346           10794   
56039      9019             84678          132531            5190   
56041      7597             63403           74938            5313   
56043      3365             54158           65496            2191   
56045      2891             57031           68877            1978   

       median_family_income  mean_family_income  
fips                                             
01001                 71103               87094  
01003                 75850               97991  
01005                 41704               56374  
01007                 57891               69316  
01009                 62295               76547  
...                     ...                 ...  
56037                 87906               97459  
56039                110667              172024  
56041                 77725               86265  
56043                 68265               77355  
56045                 78083               82193  

[3142 rows x 6 columns]

#### Next we need to parse off the FIPS ID, and reset the index to the FIPS ID.

In [10]:
acs2019_income.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3220 entries, 01001 to 72153
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   total_hh              3220 non-null   int64 
 1   median_hh_income      3220 non-null   int64 
 2   mean_hh_income        3220 non-null   int64 
 3   total_families        3220 non-null   int64 
 4   median_family_income  3220 non-null   int64 
 5   mean_family_income    3220 non-null   int64 
 6   county                3220 non-null   object
 7   state                 3220 non-null   object
dtypes: int64(6), object(2)
memory usage: 226.4+ KB


#### Then, read in the race and ethnicity by county data. We used `ACSDT5Y2019.B02001_metadata_2021-10-08T032031.csv` to identify columns of interest.

In [11]:
# Specify columns of interest.
acs2019_income_columns_of_interest = ['GEO_ID', 
                                      'NAME', 
                                      'B02001_001E', 
                                      'B02001_002E', 
                                      'B02001_003E', 
                                      'B02001_004E', 
                                      'B02001_005E', 
                                      'B02001_006E'
                                     ]

acs2019_race_ethnicity = pd.read_csv(
    '../data/02_demo_data/ACS/ACS_2019_race_and_ethnicity_by_county/ACSDT5Y2019.B02001_data_with_overlays_2021-10-08T032031.csv',
    usecols = acs2019_income_columns_of_interest,
    skiprows=[1])

# Clean up naming conventions.
acs2019_race_ethnicity.columns = ['geo_id', 
                          'name',
                          'tot_pop_race_ethnicity',
                          'tot_white',
                          'tot_black_af_am',
                          'tot_aminalnat', # American Indian and Alaska Native
                          'tot_asian',
                          'tot_hawopi' # Hawaiiwan and other Pacific Islander
                          ]
acs2019_race_ethnicity

geo_id                              name  \
0     0500000US01001           Autauga County, Alabama   
1     0500000US01003           Baldwin County, Alabama   
2     0500000US01005           Barbour County, Alabama   
3     0500000US01007              Bibb County, Alabama   
4     0500000US01009            Blount County, Alabama   
...              ...                               ...   
3215  0500000US72145  Vega Baja Municipio, Puerto Rico   
3216  0500000US72147    Vieques Municipio, Puerto Rico   
3217  0500000US72149   Villalba Municipio, Puerto Rico   
3218  0500000US72151    Yabucoa Municipio, Puerto Rico   
3219  0500000US72153      Yauco Municipio, Puerto Rico   

      tot_pop_race_ethnicity  tot_white  tot_black_af_am  tot_aminalnat  \
0                      55380      42527            10538            140   
1                     212830     183471            19718           1645   
2                      25361      11869            12066             82   
3                      22493      17272             5014             30   
4                      57681      55062              928             46   
...                      ...        ...              ...            ...   
3215                   52192      43427             2589             64   
3216                    8642       4730              651              8   
3217                   22403      12713              773              0   
3218                   33499       6244            26418              0   
3219                   35428      26607             1346            159   

      tot_asian  tot_hawopi  
0           573          26  
1          1969           9  
2           134           1  
3            27           0  
4           212          25  
...         ...         ...  
3215          9           1  
3216         14           0  
3217          0           0  
3218         11           0  
3219          6           0  

[3220 rows x 8 columns]

In [12]:
acs2019_race_ethnicity_clean = clean_acs(acs2019_race_ethnicity)
acs2019_race_ethnicity_clean.drop(columns = ['state', 'county'], inplace = True)
acs2019_race_ethnicity_clean

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


tot_pop_race_ethnicity  tot_white  tot_black_af_am  tot_aminalnat  \
fips                                                                       
01001                   55380      42527            10538            140   
01003                  212830     183471            19718           1645   
01005                   25361      11869            12066             82   
01007                   22493      17272             5014             30   
01009                   57681      55062              928             46   
...                       ...        ...              ...            ...   
56037                   43521      40642              502            508   
56039                   23280      20785              290             77   
56041                   20479      19132               23            145   
56043                    8027       7204                3             76   
56045                    7049       6867               16             12   

       tot_asian  tot_hawopi  
fips                          
01001        573          26  
01003       1969           9  
01005        134           1  
01007         27           0  
01009        212          25  
...          ...         ...  
56037        340          19  
56039        291          29  
56041         32           0  
56043          0           0  
56045         54          10  

[3142 rows x 6 columns]

### Do the same type of import and data cleanup on the ACS 2019 poverty data.

In [13]:
# Specify columns of interest.
acs2019_poverty_columns_of_interest = ['GEO_ID', 
                                      'NAME', 
                                      'S1701_C01_001E', 
                                       'S1701_C02_001E', 
                                       'S1701_C03_001E']

# Read in the data.

acs2019_poverty = pd.read_csv(
    '../data/02_demo_data/ACS/ACS_2019_poverty_by_county/ACSST5Y2019.S1701_data_with_overlays_2021-11-02T160432.csv',
    usecols = acs2019_poverty_columns_of_interest,
    skiprows = [1])

# Change the column naming conventions.
acs2019_poverty.columns = ['geo_id', 
                          'name',
                          'total_pop_poverty',
                          'pop_below_poverty',
                          'percent_below_poverty',
                          ]
acs2019_poverty.head(3)

geo_id                     name  total_pop_poverty  \
0  0500000US01001  Autauga County, Alabama              54922   
1  0500000US01003  Baldwin County, Alabama             209618   
2  0500000US01005  Barbour County, Alabama              22417   

   pop_below_poverty  percent_below_poverty  
0               8340                   15.2  
1              21704                   10.4  
2               6875                   30.7

In [14]:
acs2019_poverty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3220 entries, 0 to 3219
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   geo_id                 3220 non-null   object 
 1   name                   3220 non-null   object 
 2   total_pop_poverty      3220 non-null   int64  
 3   pop_below_poverty      3220 non-null   int64  
 4   percent_below_poverty  3220 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 125.9+ KB


In [15]:
acs2019_poverty_clean = clean_acs(acs2019_poverty)
acs2019_poverty_clean.drop(columns = ['state', 'county'], inplace = True)
acs2019_poverty_clean

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


total_pop_poverty  pop_below_poverty  percent_below_poverty
fips                                                              
01001              54922               8340                   15.2
01003             209618              21704                   10.4
01005              22417               6875                   30.7
01007              20632               3740                   18.1
01009              57108               7739                   13.6
...                  ...                ...                    ...
56037              42958               4921                   11.5
56039              23188               1426                    6.1
56041              20259               2298                   11.3
56043               7853                825                   10.5
56045               6709                971                   14.5

[3142 rows x 3 columns]

#### Read in the data from OpenIntro.org. This is an organization that created a nearly full file of data variables that many people are interested in. It is likely that many of the columns will overlap with others that we've read in from ACS data but we're grabbing them anyway because occasionally they're in a better format than the ACS data. https://www.openintro.org/data/?data=county_complete

In [16]:
county_complete_columns_of_interest = ['fips', 
                           'state', 
                           'name', 
                           'smoking_ban_2010',                                                        
                           'asian_2019', 
                           'avg_family_size_2019', 
                           'black_2019',
                           'hispanic_2019',
                           'household_has_broadband_2019', 
                           'household_has_computer_2019',
                           'household_has_smartphone_2019',
                           'households_2019',
                           'households_speak_limited_english_2019',
                           'housing_mobile_homes_2019',
                           'hs_grad_2019',                           
                           'median_household_income_2019',
                           'median_individual_income_2019',
                           'native_2019',
                           'other_single_race_2019',
                           'pac_isl_2019',
                           'persons_per_household_2019',
                           'pop_2019',
                           'unemployment_rate_2019',
                           'uninsured_2019',
                           'veterans_2019',
                           'white_2019',
                           'white_not_hispanic_2019']

county_complete = pd.read_csv(
    '../data/02_demo_data/openintro_dot_org/county_complete.csv',
    usecols = county_complete_columns_of_interest,
    converters = {'fips': lambda x: str(x)})


county_complete.info()

# Got the idea for the converters from:
# https://stackoverflow.com/questions/13250046/how-to-keep-leading-zeros-in-a-column-when-reading-csv-with-pandas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3142 entries, 0 to 3141
Data columns (total 27 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   fips                                   3142 non-null   object 
 1   state                                  3142 non-null   object 
 2   name                                   3142 non-null   object 
 3   smoking_ban_2010                       3116 non-null   object 
 4   asian_2019                             3142 non-null   float64
 5   avg_family_size_2019                   3142 non-null   float64
 6   black_2019                             3142 non-null   float64
 7   hispanic_2019                          3142 non-null   float64
 8   household_has_broadband_2019           3142 non-null   float64
 9   household_has_computer_2019            3142 non-null   float64
 10  household_has_smartphone_2019          3142 non-null   float64
 11  hous

In [17]:
county_complete.rename(columns = {'name': 'county'}, inplace = True)

county_complete['fips'] = county_complete['fips'].str.zfill(5)

# Learned about zfill() here: https://stackoverflow.com/questions/42375068/python-add-a-leading-zero-to-column-with-str-and-int
# Also here: https://www.datasciencemadesimple.com/add-leading-preceding-zeros-python/

county_complete.set_index('fips', inplace = True)
county_complete.drop(columns = ['state', 'county'], inplace = True)
county_complete

smoking_ban_2010  asian_2019  avg_family_size_2019  black_2019  \
fips                                                                   
01001             none         1.0                  3.09        19.0   
01003             none         0.9                  3.24         9.3   
01005          partial         0.5                  3.01        47.6   
01007             none         0.1                  3.74        22.3   
01009             none         0.4                  3.33         1.6   
...                ...         ...                   ...         ...   
56037             none         0.8                  3.32         1.2   
56039          partial         1.3                  3.01         1.2   
56041             none         0.2                  3.23         0.1   
56043             none         0.0                  2.89         0.0   
56045             none         0.8                  2.82         0.2   

       hispanic_2019  household_has_broadband_2019  \
fips                                                 
01001            2.8                          80.6   
01003            4.6                          81.8   
01005            4.4                          60.5   
01007            2.6                          69.2   
01009            9.3                          73.0   
...              ...                           ...   
56037           15.9                          84.0   
56039           15.0                          87.1   
56041            9.1                          89.5   
56043           14.2                          78.2   
56045            1.1                          76.8   

       household_has_computer_2019  household_has_smartphone_2019  \
fips                                                                
01001                         73.0                           78.4   
01003                         76.3                           81.7   
01005                         51.9                           64.2   
01007                         54.7                           66.6   
01009                         63.5                           70.1   
...                            ...                            ...   
56037                         81.9                           83.4   
56039                         90.1                           85.3   
56041                         80.3                           84.8   
56043                         77.2                           72.3   
56045                         74.2                           74.7   

       households_2019  households_speak_limited_english_2019  \
fips                                                            
01001            21397                                    0.7   
01003            80930                                    1.2   
01005             9345                                    1.6   
01007             6891                                    0.6   
01009            20847                                    1.8   
...                ...                                    ...   
56037            15523                                    1.9   
56039             9019                                    5.7   
56041             7597                                    0.6   
56043             3365                                    1.2   
56045             2891                                    0.0   

       housing_mobile_homes_2019  hs_grad_2019  median_household_income_2019  \
fips                                                                           
01001                       26.7          88.5                         58731   
01003                       24.8          90.8                         58320   
01005                       39.1          73.2                         32525   
01007                       25.6          79.1                         47542   
01009                       21.2          80.5                         49358   
...                          ...           ...                

#### Read in data about county classifications from: https://www.ers.usda.gov/data-products/atlas-of-rural-and-small-town-america/download-the-data/


In [18]:
county_class_columns_of_interest = ['FIPStxt', 
                                    'State', 
                                    'County',
                                    'Metro2013',
                                    'RuralUrbanContinuumCode2013', 
                                    'Retirement_Destination_2015_Update', 
                                    'Metro_Adjacent2013']

county_class = pd.read_csv(
    '../data/02_demo_data/rural_atlas_all_counties/County Classifications.csv', 
    delimiter='\t', 
    encoding_errors = 'Ignore',
    converters = {'FIPStxt': lambda x: str(x)},
    usecols = county_class_columns_of_interest)


# Note: I added the encoding_errors = 'Ignore' as a test after getting this error:
# 'utf-8' codec can't decode byte 0xf1 in position 185518: invalid continuation byte
# This was on the second pass of importing the file; the first pass yielded no errors.


In [19]:
# Fix the county column names
county_class.columns = ['fips', 'state', 'county', 'Metro2013',
                                    'rural_urban_continuum_code_2013', 
                                    'retirement_destination_2015_update', 
                                    'metro_adjacent_2013'
                       ]

# Set the index to match the other columns
county_class.set_index('fips', inplace = True)

# Drop Puerto Rico.
county_class = county_class[county_class['state'].str.contains('PR') == False]

# Drop the state and county columns as they are no longer needed and are duplicates.

county_class.drop(columns = ['state', 'county'], inplace = True)

# Note that the state and county naming conventions don't match the other data set; this doesn't matter as we will merge on the FIPS index.

In [20]:
county_class.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3147 entries, 01001 to 56045
Data columns (total 4 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   Metro2013                           3143 non-null   float64
 1   rural_urban_continuum_code_2013     3143 non-null   float64
 2   retirement_destination_2015_update  3143 non-null   float64
 3   metro_adjacent_2013                 3143 non-null   float64
dtypes: float64(4)
memory usage: 122.9+ KB


In [21]:
%who DataFrame

acs2019_age_sex	 acs2019_age_sex_clean	 acs2019_income	 acs2019_income_clean	 acs2019_poverty	 acs2019_poverty_clean	 acs2019_race_ethnicity	 acs2019_race_ethnicity_clean	 county_class	 
county_complete	 


In [22]:
dfs = [
    acs2019_age_sex_clean,
    acs2019_income_clean,
    acs2019_race_ethnicity_clean,
    acs2019_poverty_clean,
    county_complete,
    county_class, 
]


In [23]:
final_demo_df = pd.concat(dfs, axis = 1)
final_demo_df

total_pop_age_sex  median_age  sex_ratio_males  under_18_percent  \
fips                                                                      
01001            55380.0        38.2             94.7              23.8   
01003           212830.0        43.0             94.7              21.7   
01005            25361.0        40.4            112.4              20.9   
01007            22493.0        40.9            117.5              20.6   
01009            57681.0        40.7             97.6              23.2   
...                  ...         ...              ...               ...   
02010                NaN         NaN              NaN               NaN   
02201                NaN         NaN              NaN               NaN   
02232                NaN         NaN              NaN               NaN   
02280                NaN         NaN              NaN               NaN   
51515                NaN         NaN              NaN               NaN   

       over_18_percent  over_65_percent          county     state  total_hh  \
fips                                                                          
01001             76.2             15.0  Autauga County   Alabama   21397.0   
01003             78.3             20.0  Baldwin County   Alabama   80930.0   
01005             79.1             18.6  Barbour County   Alabama    9345.0   
01007             79.4             15.9     Bibb County   Alabama    6891.0   
01009             76.8             17.9   Blount County   Alabama   20847.0   
...                ...              ...             ...       ...       ...   
02010              NaN              NaN             NaN       NaN       NaN   
02201              NaN              NaN             NaN       NaN       NaN   
02232              NaN              NaN             NaN       NaN       NaN   
02280              NaN              NaN             NaN       NaN       NaN   
51515              NaN              NaN             NaN       NaN       NaN   

       median_hh_income  mean_hh_income  total_families  median_family_income  \
fips                                                                            
01001           58731.0         75326.0         15076.0               71103.0   
01003           58320.0         80986.0         53467.0               75850.0   
01005           32525.0         47068.0          6187.0               41704.0   
01007           47542.0         60182.0          4789.0               57891.0   
01009           49358.0         65639.0         14874.0               62295.0   
...                 ...             ...             ...                   ...   
02010               NaN             NaN             NaN                   NaN   
02201               NaN             NaN             NaN                   NaN   
02232               NaN             NaN             NaN                   NaN   
02280               NaN             NaN             NaN                   NaN   
51515               NaN             NaN             NaN                   NaN   

       mean_family_income  tot_pop_race_ethnicity  tot_white  tot_black_af_am  \
fips                                                                            
01001             87094.0                 55380.0    42527.0          10538.0   
01003             97991.0                212830.0   183471.0          19718.0   
01005             56374.0                 25361.0    11869.0          12066.0   
01007             69316.0                 22493.0    17272.0           5014.0   
01009             76547.0                 57681.0    55062.0            928.0   
...                   ...                     ...        ...              ...   
02010                 NaN                     NaN        NaN              NaN   
02201                 NaN                     NaN        NaN              NaN   
02232                 NaN                     NaN        NaN              NaN   
02280                 NaN                     NaN        N

#### We discovered that five FIPS codes in the `county_class` dataframe were not in the other three. See below:

In [24]:
county_class[~county_class.index.isin(acs2019_poverty.index)]

Metro2013  rural_urban_continuum_code_2013  \
fips                                                
02010        NaN                              NaN   
02201        NaN                              NaN   
02232        NaN                              NaN   
02280        NaN                              NaN   
51515        2.0                              1.0   

       retirement_destination_2015_update  metro_adjacent_2013  
fips                                                            
02010                                 NaN                  NaN  
02201                                 NaN                  NaN  
02232                                 NaN                  NaN  
02280                                 NaN                  NaN  
51515                                 0.0                  0.0

In [25]:
county_class[~county_class.index.isin(acs2019_income.index)]

Metro2013  rural_urban_continuum_code_2013  \
fips                                                
02010        NaN                              NaN   
02201        NaN                              NaN   
02232        NaN                              NaN   
02280        NaN                              NaN   
51515        2.0                              1.0   

       retirement_destination_2015_update  metro_adjacent_2013  
fips                                                            
02010                                 NaN                  NaN  
02201                                 NaN                  NaN  
02232                                 NaN                  NaN  
02280                                 NaN                  NaN  
51515                                 0.0                  0.0

In [26]:
county_class[~county_class.index.isin(county_complete.index)]

Metro2013  rural_urban_continuum_code_2013  \
fips                                                
02010        NaN                              NaN   
02201        NaN                              NaN   
02232        NaN                              NaN   
02280        NaN                              NaN   
51515        2.0                              1.0   

       retirement_destination_2015_update  metro_adjacent_2013  
fips                                                            
02010                                 NaN                  NaN  
02201                                 NaN                  NaN  
02232                                 NaN                  NaN  
02280                                 NaN                  NaN  
51515                                 0.0                  0.0

#### Here's what happened to them:
 - 02010 in Aleutian Islands, AK, became 02016. https://www.thearda.com/archive/files/descriptions/AppendixC_RCMS.pdf
 - 02201 in Prince of Wales-Outer Ketchikan: Part of this area (Outer Ketchikan) was annexed by Ketchikan Gateway Borough (FIPS code = 02130), part was included in the new Wrangell City and borough (FIPS code = 02275), and the remainder was renamed Prince of Wales-Hyder Census Area (FIPS code = 02198). https://www.cdc.gov/nchs/data/nvss/bridged_race/county_geography_changes.pdf
 - 02232 in Skagway-Hoonah-Angoon, AK was split to create Skagway Municipality (FIPS = 02230) and Hoonah-Angoon Census Area (FIPS code = 02105). https://www.cdc.gov/nchs/data/data_acces_files/County-Geography.pdf
 - 02280 in Wrangell-Petersburg, AK, was split to create part of Wrangell City and Borough (FIPS code = 02275) and all of Petersburg Census Area (FIPS code = 02195)  https://www.cdc.gov/nchs/data/data_acces_files/County-Geography.pdf
 - 51515 in Bedford, VA, was merged (Bedford city, VA (FIPS code=51515). In 2013, Bedford City, an independent city, merged
with Bedford county (FIPS code=51019) https://www.cdc.gov/nchs/data/data_acces_files/County-Geography.pdf

#### We'll just drop those five rows from the `final_demo_df`.

In [27]:
final_demo_df.drop(index=['02010', '02201', '02232', '02280', '51515'], inplace = True)

# Reset the index to pop FIPS back into the dataframe so that we can write it out to CSV and read it back in properly. 
final_demo_df.reset_index(inplace = True)

In [28]:
final_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3142 entries, 0 to 3141
Data columns (total 52 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   fips                                   3142 non-null   object 
 1   total_pop_age_sex                      3142 non-null   float64
 2   median_age                             3142 non-null   float64
 3   sex_ratio_males                        3142 non-null   float64
 4   under_18_percent                       3142 non-null   float64
 5   over_18_percent                        3142 non-null   float64
 6   over_65_percent                        3142 non-null   float64
 7   county                                 3142 non-null   object 
 8   state                                  3142 non-null   object 
 9   total_hh                               3142 non-null   float64
 10  median_hh_income                       3142 non-null   float64
 11  mean

In [29]:
final_demo_df

fips  total_pop_age_sex  median_age  sex_ratio_males  under_18_percent  \
0     01001            55380.0        38.2             94.7              23.8   
1     01003           212830.0        43.0             94.7              21.7   
2     01005            25361.0        40.4            112.4              20.9   
3     01007            22493.0        40.9            117.5              20.6   
4     01009            57681.0        40.7             97.6              23.2   
...     ...                ...         ...              ...               ...   
3137  56037            43521.0        35.3            106.8              26.5   
3138  56039            23280.0        39.3            112.5              19.1   
3139  56041            20479.0        35.8            103.3              29.2   
3140  56043             8027.0        42.9            102.6              24.6   
3141  56045             7049.0        43.1            111.7              21.0   

      over_18_percent  over_65_percent             county     state  total_hh  \
0                76.2             15.0     Autauga County   Alabama   21397.0   
1                78.3             20.0     Baldwin County   Alabama   80930.0   
2                79.1             18.6     Barbour County   Alabama    9345.0   
3                79.4             15.9        Bibb County   Alabama    6891.0   
4                76.8             17.9      Blount County   Alabama   20847.0   
...               ...              ...                ...       ...       ...   
3137             73.5             11.4  Sweetwater County   Wyoming   15523.0   
3138             80.9             14.0       Teton County   Wyoming    9019.0   
3139             70.8             13.0       Uinta County   Wyoming    7597.0   
3140             75.4             21.1    Washakie County   Wyoming    3365.0   
3141             79.0             19.4      Weston County   Wyoming    2891.0   

      median_hh_income  mean_hh_income  total_families  median_family_income  \
0              58731.0         75326.0         15076.0               71103.0   
1              58320.0         80986.0         53467.0               75850.0   
2              32525.0         47068.0          6187.0               41704.0   
3              47542.0         60182.0          4789.0               57891.0   
4              49358.0         65639.0         14874.0               62295.0   
...                ...             ...             ...                   ...   
3137           74843.0         85346.0         10794.0               87906.0   
3138           84678.0        132531.0          5190.0              110667.0   
3139           63403.0         74938.0          5313.0               77725.0   
3140           54158.0         65496.0          2191.0               68265.0   
3141           57031.0         68877.0          1978.0               78083.0   

      mean_family_income  tot_pop_race_ethnicity  tot_white  tot_black_af_am  \
0                87094.0                 55380.0    42527.0          10538.0   
1                97991.0                212830.0   183471.0          19718.0   
2                56374.0                 25361.0    11869.0          12066.0   
3                69316.0                 22493.0    17272.0           5014.0   
4                76547.0                 57681.0    55062.0            928.0   
...                  ...                     ...        ...              ...   
3137             97459.0                 43521.0    40642.0            502.0   
3138            172024.0                 23280.0    20785.0            290.0   
3139             86265.0                 20479.0    19132.0             23.0   
3140             77355.0                  8027.0     7204.0              3.0   
3141             82193.0                  7049.0     6867.0             16.0   

      tot_aminalnat  tot_asian  tot_hawopi  total_pop_poverty  \
0             140.0      573.0        26.0            54922.0   
1        

In [32]:
final_demo_df.to_csv(
    '../data/cleaned/final_demo.csv',
    index=False
)

In [33]:
test_df = pd.read_csv(
    '../data/02_demo_data/cleaned/final_demo.csv', 
    dtype = {'fips' : object}
)
    
test_df

fips  total_pop_age_sex  median_age  sex_ratio_males  under_18_percent  \
0     01001            55380.0        38.2             94.7              23.8   
1     01003           212830.0        43.0             94.7              21.7   
2     01005            25361.0        40.4            112.4              20.9   
3     01007            22493.0        40.9            117.5              20.6   
4     01009            57681.0        40.7             97.6              23.2   
...     ...                ...         ...              ...               ...   
3137  56037            43521.0        35.3            106.8              26.5   
3138  56039            23280.0        39.3            112.5              19.1   
3139  56041            20479.0        35.8            103.3              29.2   
3140  56043             8027.0        42.9            102.6              24.6   
3141  56045             7049.0        43.1            111.7              21.0   

      over_18_percent  over_65_percent             county     state  total_hh  \
0                76.2             15.0     Autauga County   Alabama   21397.0   
1                78.3             20.0     Baldwin County   Alabama   80930.0   
2                79.1             18.6     Barbour County   Alabama    9345.0   
3                79.4             15.9        Bibb County   Alabama    6891.0   
4                76.8             17.9      Blount County   Alabama   20847.0   
...               ...              ...                ...       ...       ...   
3137             73.5             11.4  Sweetwater County   Wyoming   15523.0   
3138             80.9             14.0       Teton County   Wyoming    9019.0   
3139             70.8             13.0       Uinta County   Wyoming    7597.0   
3140             75.4             21.1    Washakie County   Wyoming    3365.0   
3141             79.0             19.4      Weston County   Wyoming    2891.0   

      median_hh_income  mean_hh_income  total_families  median_family_income  \
0              58731.0         75326.0         15076.0               71103.0   
1              58320.0         80986.0         53467.0               75850.0   
2              32525.0         47068.0          6187.0               41704.0   
3              47542.0         60182.0          4789.0               57891.0   
4              49358.0         65639.0         14874.0               62295.0   
...                ...             ...             ...                   ...   
3137           74843.0         85346.0         10794.0               87906.0   
3138           84678.0        132531.0          5190.0              110667.0   
3139           63403.0         74938.0          5313.0               77725.0   
3140           54158.0         65496.0          2191.0               68265.0   
3141           57031.0         68877.0          1978.0               78083.0   

      mean_family_income  tot_pop_race_ethnicity  tot_white  tot_black_af_am  \
0                87094.0                 55380.0    42527.0          10538.0   
1                97991.0                212830.0   183471.0          19718.0   
2                56374.0                 25361.0    11869.0          12066.0   
3                69316.0                 22493.0    17272.0           5014.0   
4                76547.0                 57681.0    55062.0            928.0   
...                  ...                     ...        ...              ...   
3137             97459.0                 43521.0    40642.0            502.0   
3138            172024.0                 23280.0    20785.0            290.0   
3139             86265.0                 20479.0    19132.0             23.0   
3140             77355.0                  8027.0     7204.0              3.0   
3141             82193.0                  7049.0     6867.0             16.0   

      tot_aminalnat  tot_asian  tot_hawopi  total_pop_poverty  \
0             140.0      573.0        26.0            54922.0   
1        